version = 0.1
[default.deploy.parameters]
stack_name = "expense-api"
resolve_s3 = true
s3_prefix = "expense-api"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppOrigin=\"http://localhost:3000\""
image_repositories = []
disable_rollback = true
